name: CI
on:
  push:
    branches: [main]

jobs:
  repo:
    runs-on: ubuntu-latest
    steps:
      - name: repository download
        uses: actions/checkout@v4

      - name: node.js download
        uses: actions/setup-node@v3
        with:
          node-version: '18'